export const dummyProjects = [
  {
    id: "proj-1",
    name: "Website E-Commerce",
    deadline: "2024-02-15",
    status: "aktif",
    manager: "John Doe",
    description: "Pengembangan website e-commerce untuk toko online",
    progress: 75,
  },
  {
    id: "proj-2",
    name: "Mobile App TaskSync",
    deadline: "2024-03-01",
    status: "aktif",
    manager: "Jane Smith",
    description: "Aplikasi mobile untuk manajemen tugas",
    progress: 45,
  },
  {
    id: "proj-3",
    name: "Dashboard Analytics",
    deadline: "2024-01-30",
    status: "selesai",
    manager: "Bob Wilson",
    description: "Dashboard untuk analisis data bisnis",
    progress: 100,
  },
  {
    id: "proj-4",
    name: "API Integration",
    deadline: "2024-02-28",
    status: "aktif",
    manager: "Alice Brown",
    description: "Integrasi API dengan sistem eksternal",
    progress: 30,
  },
  {
    id: "proj-5",
    name: "Sistem Manajemen Inventaris",
    deadline: "2024-04-10",
    status: "tertunda",
    manager: "Charlie Green",
    description: "Pengembangan sistem untuk mengelola inventaris gudang",
    progress: 10,
  },
]

export const dummyTasks = [
  {
    id: "task-1",
    projectId: "proj-1",
    title: "Desain UI Homepage",
    project: "Website E-Commerce",
    deadline: "2024-01-28",
    status: "belum_selesai",
    priority: "tinggi",
    description: "Membuat desain UI untuk halaman utama website",
  },
  {
    id: "task-2",
    projectId: "proj-1",
    title: "Setup Database",
    project: "Website E-Commerce",
    deadline: "2024-01-25",
    status: "selesai",
    priority: "tinggi",
    description: "Konfigurasi database untuk aplikasi",
  },
  {
    id: "task-3",
    projectId: "proj-2",
    title: "Implementasi Login",
    project: "Mobile App TaskSync",
    deadline: "2024-01-30",
    status: "belum_selesai",
    priority: "sedang",
    description: "Membuat fitur login untuk aplikasi mobile",
  },
  {
    id: "task-4",
    projectId: "proj-4",
    title: "Testing API",
    project: "API Integration",
    deadline: "2024-02-05",
    status: "belum_selesai",
    priority: "rendah",
    description: "Testing semua endpoint API",
  },
  {
    id: "task-5",
    projectId: "proj-3",
    title: "Dokumentasi",
    project: "Dashboard Analytics",
    deadline: "2024-01-20",
    status: "selesai",
    priority: "sedang",
    description: "Membuat dokumentasi lengkap project",
  },
  {
    id: "task-6",
    projectId: "proj-1",
    title: "Integrasi Payment Gateway",
    project: "Website E-Commerce",
    deadline: "2024-02-10",
    status: "belum_selesai",
    priority: "tinggi",
    description: "Mengintegrasikan sistem pembayaran",
  },
  {
    id: "task-7",
    projectId: "proj-2",
    title: "Desain UX Mobile",
    project: "Mobile App TaskSync",
    deadline: "2024-02-15",
    status: "belum_selesai",
    priority: "sedang",
    description: "Membuat desain pengalaman pengguna untuk aplikasi mobile",
  },
]

export const dummyUser = {
  id: "user123",
  name: "Ahmad Rizki",
  email: "ahmad.rizki@example.com",
  role: "User",
  joinedAt: "2023-06-15",
  avatar: "AR",
  totalProjects: 4,
  totalTasks: 5,
  completedTasks: 2,
}

export const dummyFriends = [
  {
    id: "user-2", // Changed to match dummyAllUsers IDs
    name: "Budi Santoso",
    avatar: "BS",
    status: "Online",
  },
  {
    id: "user-3", // Changed to match dummyAllUsers IDs
    name: "Citra Dewi",
    avatar: "CD",
    status: "Offline",
  },
  {
    id: "user-5", // Changed to match dummyAllUsers IDs
    name: "Fani Lestari",
    avatar: "FL",
    status: "Online",
  },
]

export const dummyAllUsers = [
  {
    id: "user-1",
    name: "Ahmad Rizki",
    email: "ahmad.rizki@example.com",
    role: "User",
    avatar: "AR",
  },
  {
    id: "user-2",
    name: "Budi Santoso",
    email: "budi.santoso@example.com",
    role: "Developer",
    avatar: "BS",
  },
  {
    id: "user-3",
    name: "Citra Dewi",
    email: "citra.dewi@example.com",
    role: "Designer",
    avatar: "CD",
  },
  {
    id: "user-4",
    name: "Dian Permata",
    email: "dian.permata@example.com",
    role: "Project Manager",
    avatar: "DP",
  },
  {
    id: "user-5",
    name: "Eko Prasetyo",
    email: "eko.prasetyo@example.com",
    role: "QA Engineer",
    avatar: "EP",
  },
  {
    id: "user-6",
    name: "Fani Lestari",
    email: "fani.lestari@example.com",
    role: "Marketing",
    avatar: "FL",
  },
  {
    id: "user-7",
    name: "Gita Rahmawati",
    email: "gita.rahmawati@example.com",
    role: "Developer",
    avatar: "GR",
  },
  {
    id: "user-8",
    name: "Hadi Wijaya",
    email: "hadi.wijaya@example.com",
    role: "Designer",
    avatar: "HW",
  },
]
